name: Build Extension (reusable workflow)

on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment"
        type: string
        required: true

jobs:
  build-chrome-extension:
    environment: ${{ inputs.environment }}
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: load environment variables for build
        run: |
          touch .env.${{ inputs.environment }}.private
          echo SENTRY_AUTH_TOKEN="${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env.${{ inputs.environment }}.private

          touch .env.${{ inputs.environment }}.public
          echo API_BASE_URL="${{ vars.API_BASE_URL }}" >> .env.${{ inputs.environment }}.public
          echo SENTRY_ENV="${{ inputs.environment }}" >> .env.${{ inputs.environment }}.public
          echo SENTRY_DSN="${{ vars.SENTRY_DSN }}" >> .env.${{ inputs.environment }}.public

      - name: Build extension
        run: |
          NODE_ENV=${{ inputs.environment }} webpack --config webpack.prod.js
          zip -r coauthor-${{ github.event.pull_request.head.sha }}.zip build

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: coauthor-${{ github.sha }}
          path: coauthor-${{ github.event.pull_request.head.sha }}.zip

