name: Create new release

on:
  push:
    branches:
      - main

jobs:
  check-for-version-bump:
    name: "Check for version bump"
    runs-on: ubuntu-latest
    outputs:
      version-bump-found: ${{ steps.step1.outputs.VERSION_BUMP_FOUND }}
      version: ${{ steps.step1.outputs.VERSION }}
    steps:
      - name: Parse commit message for version
        id: step1
        run: |
          set +e 
          COMMIT_MESSAGE_HEADER=$(echo "${{github.event.head_commit.message}}" | head -n 1)
          match=$(echo $COMMIT_MESSAGE_HEADER | grep -E -o "chore: bump version \([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\)") 
          version=$(echo $match | grep -E -o "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+") 
          version_bump_found=$(echo $?)
          echo "VERSION_BUMP_FOUND=$version_bump_found" >> $GITHUB_OUTPUT
          echo "VERSION=$version" >> $GITHUB_OUTPUT

  build-chrome-extension:
    name: Build extension
    needs: [check-for-version-bump]
    if: needs.check-for-version-bump.outputs.version-bump-found == '0'
    uses: ./.github/workflows/build-extension-reusable.yml
    with:
      environment: production
      archive-name: coauthor-${{needs.check-for-version-bump.outputs.version}}
    secrets: inherit

  upload-extension:
    name: Upload extension to chrome web store
    needs: [build-chrome-extension, check-for-version-bump]
    runs-on: ubuntu-latest
    steps:
      # must use this to access previously uploaded artifact
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: coauthor-${{needs.check-for-version-bump.outputs.version}}
          path: ./build

      # download artifact action unzips on download (not configurable) so must zip up again
      - name: Archive build
        run: |
          zip -r coauthor-${{needs.check-for-version-bump.outputs.version}}.zip build

      - name: Install webstore cli
        run: |
          npm install -g chrome-webstore-upload-cli@3.3.1

      - name: Upload step
        run: |
          chrome-webstore-upload \
            --source coauthor-${{needs.check-for-version-bump.outputs.version}}.zip \
            --extension-id ${{ vars.EXTENSION_ID }} \
            --client-id ${{ secrets.CI_GOOGLE_OAUTH_CLIENT_ID }} \
            --client-secret ${{ secrets.CI_GOOGLE_OAUTH_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CI_GOOGLE_OAUTH_REFRESH_TOKEN }}

  push-tag:
    name: Push Tag
    needs: [check-for-version-bump, upload-extension]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ needs.check-for-version-bump.outputs.version }}
          git push origin ${{ needs.check-for-version-bump.outputs.version }}

  # Intentionally made a draft release instead of a official release
  # because the release shouldn't be finalized and made public
  # until we know for sure that the extension has been approved
  # and published (It could be rejected after uploading)
  create-draft-release:
    name: Create draft release
    needs: [push-tag, check-for-version-bump]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            coauthor-${{needs.check-for-version-bump.outputs.version}}.zip
          draft: true
          generate_release_notes: true
          tag_name: ${{needs.check-for-version-bump.outputs.version}}
          name: ${{needs.check-for-version-bump.outputs.version}}
